# Generated by Django 5.0.2 on 2024-09-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=1, max_digits=3)),
                ('longitude', models.DecimalField(decimal_places=1, max_digits=4)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_run.run')),
            ],
        ),
    ]
