# Generated by Django 5.0.2 on 2024-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_alter_position_latitude_alter_position_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
