# Generated by Django 5.0.2 on 2024-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_run_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
