# Generated by Django 5.0.2 on 2024-10-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
