# Generated by Django 5.0.2 on 2024-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_position_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Инициализация забега'), ('in_progress', 'Забег в процессе'), ('finished', 'Забег окончен')], default='init', max_length=30),
        ),
    ]
