# Generated by Django 5.0.2 on 2024-10-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_alter_run_run_time_seconds_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
