# Generated by Django 5.0.2 on 2024-10-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_run_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='speed',
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
