# Generated by Django 5.0.2 on 2024-10-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_position_distance_run_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
