# Generated by Django 5.0.2 on 2024-10-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_alter_run_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
