# Generated by Django 5.0.2 on 2024-11-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0020_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
