# Generated by Django 5.0.2 on 2024-11-19 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_subscription_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
