# Generated by Django 5.0.2 on 2024-11-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0022_alter_subscription_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
