# Generated by Django 5.0.2 on 2024-12-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0024_athleteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
