# Generated by Django 5.0.2 on 2024-12-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0025_alter_athleteinfo_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
