# Generated by Django 5.0.2 on 2024-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0026_rename_user_id_athleteinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('picture', models.URLField()),
                ('value', models.IntegerField(null=True)),
            ],
        ),
    ]
