# Generated by Django 5.0.2 on 2024-12-12 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0029_itemathletrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='collectibleitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ItemAthletRelation',
        ),
    ]
