# Generated by Django 5.0.2 on 2024-12-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0030_collectibleitem_user_delete_itemathletrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectibleitem',
            old_name='user',
            new_name='users',
        ),
    ]
