# Generated by Django 5.0.2 on 2024-08-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaika', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
