# Generated by Django 5.0.2 on 2024-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaika', '0002_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='m',
            field=models.IntegerField(default=0),
        ),
    ]
