# Generated by Django 5.0.2 on 2024-08-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaika', '0003_auto_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='m',
        ),
        migrations.AddField(
            model_name='auto',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
